# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wasif Hyder
email: wasif_hyder@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  The blog, portfolio & resume of Wasif Hyder.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wasifhyder.com" # the base hostname & protocol for your site
twitter_username: wasif_hyder
github_username:  wasifhyder

# Build settings
markdown: kramdown
